"use strict";
exports.__esModule = true;
var button_1 = require("@lion/button");
var button_js_1 = require("@lion/ui/exports/button.js");
var button_2 = require("local-lion-ui/exports/button");
var local_button_1 = require("local-button");
customElements.define('old-button', button_1.LionButton);
customElements.define('new-button', button_js_1.LionButton);
customElements.define('local-button', local_button_1.LocalButton);
customElements.define('local-lion-button', button_2.LionButton);
